#!/bin/bash
# Dont allow commits containing the addition of '@wip'

if test "$(git diff --cached | grep -P '\+\s*@wip')"
then
  echo "Error: Attempt to commit an @wip line"
  echo
  echo "To skip this check, add the --no-verify option"
  echo
  exit 1
fi

# Dont allow commits containing trailing whitespace

if test "$(git diff --cached | grep -P '\+.*( |\t)$')"
then
  echo "Error: Attempt to commit trailing whitespace"
  echo
  echo "To skip this check, add the --no-verify option"
  echo
  exit 1
fi
