#!/usr/bin/env ruby
# A script for storing secrets in GPG encrypted files
#
# Requires the GPGME gem:
# https://github.com/ueno/ruby-gpgme

$LOAD_PATH.unshift File.expand_path('../../.lib/ruby', __FILE__)

require 'pw'

begin
  pw = PW.new(
    ARGV,
    File.expand_path('../../.db', __FILE__)
  )

  pw.run
rescue Errno::ENOENT
  $stderr.puts "ERROR: Unknown db or key"
  exit 1
rescue PW::KeyExists
  $stderr.puts "ERROR: key exists"
  exit 1
end
