#!/usr/bin/env ruby
# Set a secret in a pw database
#
# Uses the python gkeyring script:
# https://github.com/kparal/gkeyring

def require_gem(name)
  require name
rescue LoadError
  $stderr.puts "** ERROR ** The #{name} gem is missing"
  exit 1
end

db_dir  = File.expand_path('../../.db', __FILE__)
db_name = ARGV.shift
db_path = "#{db_dir}/#{db_name}.db"

unless File.exists?(db_path)
  $stderr.puts %{Unknown pw database "#{db_name}"}
  exit 1
end

require_gem 'sqlite3'
db = SQLite3::Database.new db_path

pass = `gkeyring -p type=pw,name=pw:#{db_name} -o secret`.strip

if pass.empty?
  # This shouldn't happen
  $stderr.puts %{Could not get pass for "#{db_name}"}
  exit 1
end

db.execute "PRAGMA key = '#{pass}';"

name, secret = ARGV.shift(2)

if secret.nil?
  require 'securerandom'
  secret = SecureRandom.hex
end

if db.get_first_value("select secret from secrets where name = ?", name).nil?
  db.execute("insert into secrets values ( ?, ? )", name, secret)
else
  $stderr.puts %{Secret "#{name}" already exists}
  exit 1
end
